#!/bin/bash
sudo apt-get install mysql-client
docker pull mysql
docker run -p 3306:3306 --name mysql-docker-local -e MYSQL_ROOT_PASSWORD=Password -d mysql:latest --bind-address=0.0.0.0
while ! mysqladmin ping --host=52.210.248.234 --silent; do
    sleep 1
done
sudo mysql --host=52.210.248.234 --port=3306 -u root -pPassword <user.sql
sudo mysql petclinic --host=52.210.248.234 --port=3306 -u root -pPassword <schemas.sql
sudo mysql petclinic --host=52.210.248.234 --port=3306 -u root -pPassword <data.sql
